name: ngaos_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.2.3 <4.0.0'

dependencies:
    bloc: ^8.1.3
    dynamic_color: ^1.7.0
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.4
    flutter_islamic_icons: ^1.0.2
    flutter_svg: ^2.0.10+1
    go_router: ^13.2.0
    http: ^1.2.0
    infinite_scroll_pagination: ^4.0.0
    just_audio: ^0.9.37

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/svgs/
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Bold.ttf
              - asset: assets/fonts/Poppins-Medium.ttf
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-SemiBold.ttf
        - family: Lato
          fonts:
              - asset: assets/fonts/Lato-Regular.ttf
              - asset: assets/fonts/Lato-Bold.ttf
              - asset: assets/fonts/Lato-Black.ttf
        - family: Lpmq
          fonts:
              - asset: assets/fonts/lpmq_quran.ttf
